version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build || echo No build step defined, skipping...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Zipping source files...
      - zip -r app.zip . 
artifacts:
  files:
    - app.zip
    - appspec.yml
    - scripts/**/*
    - node_modules/**/*
    - package.json
